### PR TITLE
adding queer.family pub

### PR DESCRIPTION
**Pull request by rabble**
pretty straight forward, well not so straight, but you get the point. New pub for queer people

### CODE REVIEW

**Comment by mplorentz** [comment]
We were having some CI problems on `main` but they are fixed now. If you merge `main` into this branch the tests should start passing again.

**Comment by mplorentz** [comment]
I'm seeing queer.family in my network tab but it looks like the invitation didn't get embedded. I'll add it and also write up the steps to adding a preloaded pub to the iOS app.

**Comment by teohhanhui** [comment]
Is the invite still valid?

```
queer.family:8008:@nnAMmrhLfy54wkYSgAZWK4fBg/b/83YjilPk5JfNzXM=.ed25519~kxCY33m5QNMnLbJ0pkHHUaWdRyANTlS4gaISXN2D3x0=
```

I tried pasting that in Manyverse but it says "invite rejected" 😅

**Comment by mplorentz** [comment]
Hi @teohhanhui, sorry for the delay. I didn't see this until just now. I checked the invite and it still works. I think Manyverse has problems redeeming pub invites at the moment. I have filed a ticket with them [here](https://gitlab.com/staltz/manyverse/-/issues/1824#note_1095865538).

**Pull request merged**
