### PR TITLE
adding preloaded profile icons for chinese and french pubs

### PR DESCRIPTION
**Pull request by rabble**
super simple, just adds the pub icons for french and chinese.

### CODE REVIEW

**Review by mplorentz — CHANGES_REQUESTED** [review]
It looks like the actual image files didn't get added to the repo. Did you forget to commit them?

**Comment by mplorentz** [comment]
Also the unit tests are saying that one of the preloaded feeds are invalid JSON.

**Comment by martindsq** [comment]
@mplorentz I think this work needs to be done in the other PR, #772, because we are adding the same pubs here and that other PR has the addition of actually adding those pubs in the xcconfig files

**Comment by mplorentz** [comment]
Ok, I copied some of these changes over to #772 and merged it. This PR is no longer necessary I think.

**Pull request closed without merging**
