### PR TITLE
Update colors of navigation bar and tab bars

### LINKED ISSUE #1059: change colors in uikit to match new color scheme in swift ui
Let's change the accent and background colors to match the new swiftUI message cell designs

### PR DESCRIPTION
**Pull request by martindsq**
Closes #1059 

- [X] Update color of the navigation bar
- [X] Update color of the search bar
- [X] Update color of the tab bar
- [X] Remove unused colors
- [x] Update tab bar icons

IMG_3490B8B48217-1

### CODE REVIEW

**Review by mplorentz — APPROVED** [review]
Let's SHIP IT 🚢 ! This makes it feel like a whole new app (even though we still have a few more places to update colors)

**Comment by mplorentz** [comment]
I think we shouldn't close #1059 right after merging this though. Some places I noticed we still need new colors:
- Settings
- Notifications tab still uses purple accent
- Your Network tab still uses purple accent
- Thread view has wrong background color in light mode.

**Comment by martindsq** [comment]
> I think we shouldn't close #1059 right after merging this though. Some places I noticed we still need new colors:
> 
>     * Settings
> 
>     * Notifications tab still uses purple accent
> 
>     * Your Network tab still uses purple accent
> 
>     * Thread view has wrong background color in light mode.
> 
>     * New Post screen

The intent behing that issue was what I did, quickly update the navigation bar colors so that they use the new colors we have been using in swiftui. If you are ok with this, I'll close that issue after merging this one, but I'm creating a new issue that a checklist (I'd add the left menu as well that still has the purple)

**Comment by martindsq** [comment]
I created this other issue for that: https://github.com/planetary-social/planetary-ios/issues/1099

**Pull request merged**
