### PR TITLE
Fix deadlock in go-ssb

### PR DESCRIPTION
**Pull request by boreq**
Related to #576.

### CODE REVIEW

**Comment by boreq** [comment]
Weird... tests failed but maybe it is an intermittent failure.

**Comment by mplorentz** [comment]
I hate to report it but this branch did get stuck for me ☹️. I made sure to clean and rebuild go-ssb, and then built it again for good measure. I deleted and reinstalled Planetary using this branch and it replicated about 35k messages before it locked up. I restarted the app and it went about another 30k and got stuck again.

**Comment by boreq** [comment]
Just to be clear this fixes the problem where there is a deadlock which also causes the peer list to no longer be refreshed. Has this also happened for you on top of the replication stopping?

**Comment by boreq** [comment]
Ok, it just happened to me again, I think there are more mutex-related bugs in that code.

**Pull request merged**
