### PR TITLE
Update the tap target on the Edit profile page

### PR DESCRIPTION
**Pull request by czuria1**
As discussed in #460, I have changed the view to match the UI changes which include:
- The text area of the bio will covers the entire page
- The text inputs have rounded borders
- The text view for the bio will adapt to the keyboard when it shows up

| | |
| --- | --- |
|  |  |

| | | |
| --- | --- | --- |
|  |  |  |

### CODE REVIEW

**Comment by czuria1** [comment]
@mplorentz @Chardot would appreciate a review and feedback on the behavior and look for the bio view!

**Comment by wsarles** [comment]
@czuria1 This looks great! There are just a couple things that need looked at before we can merge, but I wanted to make sure you got credit for #hacktoberfest!

**Review by wsarles — APPROVED** [review]

**Comment by wsarles** [comment]
@czuria1 Thanks for updating the changelog and adding your new file to the UnitTest target - much appreciated! However, there's some logic that needs to be looked at for enabling the Save button. I started off with a blank profile and tried to enter my name and bio but couldn't save. 

image

**Review by wsarles — CHANGES_REQUESTED** [review]
Enabling of the save button needs some revision.

**Review by wsarles — APPROVED** [review]

**Comment by wsarles** [comment]
@czuria1 Thank you so much for your contribution to Planetary! 🎉

**Pull request merged**
