### PR TITLE
Add the option to reset the Forked Feed Protection when it is triggered

### LINKED ISSUE #1162: Show a better description when triggering the forked feed protection
Right now we display an alert saying

> Planetary is currently restoring your data from the network, and cannot publish new posts at this time.

We should show more information, like, what happened, and how to reset the forked feed protection (directions to the debug menu maybe).

### PR DESCRIPTION
**Pull request by martindsq**
Closes #1162 

File
File(1)

### CODE REVIEW

**Comment by mplorentz** [comment]
Can you add a "more info" button to the alert that opens https://github.com/planetary-social/planetary-ios/wiki/Forked-Feed?

**Comment by boreq** [comment]
What is the status on this one? I understand we wanted to change the copy or something like that and this shouldn't be merged?

**Comment by martindsq** [comment]
@boreq its ready to be merged. I'm only waiting for the unit tests to go green

**Comment by boreq** [comment]
Oh right sorry, I thought you are waiting for some design work.

**Pull request merged**
