### PR TITLE
Add a function which returns raw messages to the bindings

### PR DESCRIPTION
**Pull request by boreq**
Related to #662.

### CODE REVIEW

**Comment by boreq** [comment]
Let me know if the function signature is acceptable @martindsq.

**Comment by martindsq** [comment]
> Let me know if the function signature is acceptable @martindsq.

I agree that get the message using a message ref is better, but the signature you choose is acceptable given that we store the sequence and the feed ref for every message in the database.

**Review by martindsq — APPROVED** [review]
Seems fine to me. It will be fine to merge after the codacy issue is fixed and a skip changelog tag as added to the PR

**Comment by boreq** [comment]
> Seems fine to me. It will be fine to merge after the codacy issue is fixed and a skip changelog tag as added to the PR

Codacy is worried that a file that was just added increased complexity from 0 (file didn't exist) to 11 (whatever that means). I don't really know how to skip any of those warnings frankly.

https://github.com/planetary-social/planetary-ios/pull/845/checks?check_run_id=8376269715

**Pull request merged**
