### PR TITLE
Post blobs as mentions

### PR DESCRIPTION
**Pull request by cryptix**
This is for compatibility with other ssb clients.

I think there is a duplication in the image carousel but nearly done.

### CODE REVIEW

**Comment by cryptix** [comment]
This still needs some love to not show that append text in the app.

**Comment by rabble** [comment]
Is this ready to merge and push to testing?

**Comment by martindsq** [comment]
ViewDatabaseTest.test61_has_blobs() is failing in UnitTests

**Comment by martindsq** [comment]
Posting an image in Planetary and seeing it in Patchwork now works!

**Comment by martindsq** [comment]
> This still needs some love to not show that append text in the app.

I created a ticket in Asana for this so feel free to merge this branch after that test is fixed.

**Pull request merged**
